name: 📜 Lore / Worldbuilding
description: Add or refine lore, history, myths, deities, or cultural elements of the world.
title: "[LORE] "
type: Lore
labels: [lore]
body:
  - type: markdown
    attributes:
      value: |
        Use this for **worldbuilding, myths, cultures, religions, and geography**.
        Examples: The Broken Moon, Elyndra’s Faith, Sakaar’s Founding, Riverfolk Traditions.
  - type: input
    id: focus
    attributes:
      label: Focus Area
      placeholder: e.g., Broken Moon, Elyndra, River Run
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Write the main lore entry or describe what needs expanding.
  - type: textarea
    id: connections
    attributes:
      label: Connections
      description: List related NPCs, locations, or events that tie into this lore.
      placeholder: e.g., Connected to Jade Tempesta, Festival of the Grandmaster
