name: ⚔️ Quest / Adventure
description: Create or update a playable session or adventure module.
title: "[QUEST] "
type: "Quest / Adventure"
labels: [adventure, encounter]
body:
  - type: markdown
    attributes:
      value: |
        For DM prep, narrative seeds, or full adventure modules.
  - type: input
    id: title
    attributes:
      label: Adventure Title
      placeholder: e.g., Growing the Garden — Dragon's Blood Seeds
  - type: textarea
    id: premise
    attributes:
      label: Premise / Hook
      description: What sets this adventure in motion?
    validations:
      required: true
  - type: textarea
    id: key-elements
    attributes:
      label: Key Elements
      description: NPCs, encounters, rewards, or related events.
