name: 🔄 Weekly GitHub Org Sync

on:
  schedule:
    - cron: "0 3 * * 0"   # Sundays 03:00 UTC
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ⚙️ Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git gh jq
          export GH_TOKEN="${{ secrets.GH_TOKEN }}"
          gh auth login --hostname github.com --with-token <<< "${GH_TOKEN}"
          gh auth setup-git
          gh auth status -t

      - name: 🔮 Run unified sync-core.ps1
        shell: pwsh
        run: |
          chmod +x .github/admin/*.ps1
          cd .github/admin
          pwsh -ExecutionPolicy Bypass -File ./sync-core.ps1 | Tee-Object -FilePath ../../sync-output.txt

      - name: 🧾 Commit sync log
        shell: bash
        run: |
          cd "${GITHUB_WORKSPACE}"
          NOW=$(date -u +"%Y-%m-%d %H:%M UTC")
          echo "## 🔄 Sync log ($NOW)" > sync-log.md
          echo '```text' >> sync-log.md
          cat sync-output.txt >> sync-log.md
          echo '```' >> sync-log.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sync-log.md
          git diff --quiet --cached || git commit -m "📜 Auto-sync log ($NOW)"
          git push origin HEAD
