name: 🔄 Weekly GitHub Org Sync

on:
  schedule:
    - cron: "0 3 * * 0"   # Sundays 03:00 UTC
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - ".github/**"
      - ".github/admin/**"
      - "CONTRIBUTING.md"
      - "SECURITY.md"
      - "CODE_OF_CONDUCT.md"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ⚙️ Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git gh jq perl
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
          gh auth status -t

      - name: 🧩 Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: 🔮 Run unified sync-core.sh
        shell: bash
        run: |
          cd admin
          # Convert Windows (CRLF) endings to Unix (LF) to avoid $'\r' errors
          find . -type f -name "*.sh" -exec sed -i 's/\r$//' {} \;
          chmod +x *.sh
          bash sync-core.sh | tee ../../sync-output.txt

      - name: 🧾 Commit sync log
        shell: bash
        run: |
          cd "${GITHUB_WORKSPACE}"
          NOW=$(date -u +"%Y-%m-%d %H:%M UTC")
          echo "## Weekly GitHub Org Sync Log ($NOW)" > sync-log.md
          echo '```text' >> sync-log.md
          cat sync-output.txt >> sync-log.md
          echo '```' >> sync-log.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sync-log.md
          git diff --quiet --cached || git commit -m "Auto-sync log ($NOW)"
          git push origin HEAD
