name: 🔁 Update Submodules - Weekly

on:
  push:
    branches: [ main, master ]
    paths:
      - ".github/workflows/update-submodules-weekly.yml"
  schedule:
    - cron: "0 10 * * 0"   # Sundays 10:00 UTC

jobs:
  trigger:
    name: ⏰
    if: ${{ !endsWith(github.repository, '/.github') }}
    uses: ./.github/workflows/update-submodules.yml
    secrets: inherit
